services:
  ccdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ccdb
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AwesomePass_1234
    restart: always

  cakecrafter_backend:
    depends_on:
      - ccdb
    build:
      context: ./CakeCrafter.Backend
    container_name: cakecrafter_backend
    ports:
      - "5010:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000

  cakecrafter_frontend:
    build:
      context: ./CakeCrafter.Frontend
    container_name: cakecrafter_frontend
    image: emstd/cakecrafter_frontend:runtime
    ports:
      - "8080:4173"