# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "CakeCrafter.Frontend/**"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - "CakeCrafter.Frontend/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore CakeCrafter.Backend/CakeCrafter.sln
    - name: Build
      run: dotnet build CakeCrafter.Backend/CakeCrafter.sln --no-restore

  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: dotnet test CakeCrafter.Backend/CakeCrafter.UnitTests/CakeCrafter.UnitTests.csproj --verbosity normal
